`impl Clone` + `std` feature flag
Kixunil/dangerous_option pull request #5
Opened 2017-06-20 04:37 UTC by dpc

Start work on #4

2017-06-20 09:48 UTC, Kixunil requested changes
Thank you for PR!

Please remove dependency on `std`. Use `#[derive()]` unless you have a reason not to.

2017-06-20 09:48 UTC, Kixunil commented on src/lib.rs
> +#[cfg(feature = "std")]
No need for this. `core` has `Clone` too.

2017-06-20 09:48 UTC, Kixunil commented on src/lib.rs
> +impl<T : Clone, H: ExceptionHandler> std::clone::Clone for DangerousOption<T, H> {
Why not use `#[derive(Clone)]`?

2017-06-21 03:26 UTC, dpc commented
How about now? Can't use `derive` as phanton type does not impl `Clone`.

2017-06-21 07:29 UTC, Kixunil approved these changes
OK, thanks!

2017-06-21 07:29 UTC, merged